### ISSUE TITLE
No such command "deploy"

### ISSUE THREAD

**Issue by mjsweet** [ryansb/hugo-lambda#5]
When I run "make deploy" I get the following error:

```
cd generate && kappa config.yml deploy && kappa config.yml add_event_sources
Usage: kappa [OPTIONS] CONFIG COMMAND [ARGS]...

Error: No such command "deploy".
make: *** [kappa] Error 2
```

Any thoughts on what the issue would be here? Does hugo-lambda need to support the latest version of Kappa? Is the deploy command deprecated?

**Comment by ryansb** [comment]
Thanks for filing a bug! I guess I haven't updated my kappa version locally so I didn't hit this. 

I see what happened, looks like kappa killed the "deploy"  command in favor of separating the event source and code updates. You'll need a config.yml with the stuff from your environment filled in (see [Kappa's example](https://github.com/garnaat/kappa/tree/develop/samples/s3)). For now, you can manually run: 

```
make deps
kappa config.yml create
kappa config.yml add_event_sources
make template
```

And I'll fix the makefile to comply with the new version in the next few days.

**Comment by vitr** [comment]
just tried your workaround and got this

```
root@vagrant-ubuntu-trusty-64:/vagrant/hugo-lambda# cd ./generate/
root@vagrant-ubuntu-trusty-64:/vagrant/hugo-lambda/generate# kappa config.yml create
creating...
Traceback (most recent call last):
  File "/usr/local/bin/kappa", line 4, in <module>
    __import__('pkg_resources').run_script('kappa==0.3.1', 'kappa')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 735, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1652, in run_script
  File "/usr/local/lib/python2.7/dist-packages/kappa-0.3.1-py2.7.egg/EGG-INFO/scripts/kappa", line 155, in <module>
    cli(obj={})
  File "/usr/local/lib/python2.7/dist-packages/click-4.0-py2.7.egg/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-4.0-py2.7.egg/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-4.0-py2.7.egg/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click-4.0-py2.7.egg/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click-4.0-py2.7.egg/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kappa-0.3.1-py2.7.egg/EGG-INFO/scripts/kappa", line 45, in create
    context.create()
  File "/usr/local/lib/python2.7/dist-packages/kappa-0.3.1-py2.7.egg/kappa/context.py", line 135, in create
    self.function.create()
  File "/usr/local/lib/python2.7/dist-packages/kappa-0.3.1-py2.7.egg/kappa/function.py", line 150, in create
    exec_role = self._context.exec_role_arn
  File "/usr/local/lib/python2.7/dist-packages/kappa-0.3.1-py2.7.egg/kappa/context.py", line 66, in exec_role_arn
    return self.role.arn
AttributeError: 'NoneType' object has no attribute 'arn'


```

should I change something in the `sample.json`?

**Comment by ryansb** [comment]
No, it's not a sample.json issue. I've just pushed updates to `master` that make hugo-lambda compatible with the latest kappa. 

Can you try pulling the changes and let me know if they work for you? @mjsweet @vitr

**Comment by vitr** [comment]
nope, I've made a clean copy of hugo-lambda and run `make deploy`. I suspect the first client error is the cause of all troubles, nevertheless I increased the timeout to 260, so the stack is surely created (I checked manually).

```
All deps are ready
Generated CFN template

A client error (ValidationError) occurred when calling the DescribeStackResources operation: Stack with id HugoSiteStack does not exist
aws cloudformation create-stack --stack-name HugoSiteStack --template-body file://hugo-lambda.cfn --capabilities CAPABILITY_IAM
{
    "StackId": "arn:aws:cloudformation:us-east-1:021539352183:stack/HugoSiteStack/a0788220-3fb9-11e5-a489-50e2415c7290"
}
sleep 260 # wait for the stack to be created, we need the IAM role to exist for the next steps
sed -i -e s/EXECROLE// generate/config.yml
cd generate && kappa config.yml create && kappa config.yml add_event_sources
creating...
Traceback (most recent call last):
  File "/usr/local/bin/kappa", line 4, in <module>
    __import__('pkg_resources').run_script('kappa==0.3.1', 'kappa')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 735, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1652, in run_script
  File "/usr/local/lib/python2.7/dist-packages/kappa-0.3.1-py2.7.egg/EGG-INFO/scripts/kappa", line 155, in <module>
    cli(obj={})
  File "/usr/local/lib/python2.7/dist-packages/click-4.0-py2.7.egg/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-4.0-py2.7.egg/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-4.0-py2.7.egg/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click-4.0-py2.7.egg/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click-4.0-py2.7.egg/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kappa-0.3.1-py2.7.egg/EGG-INFO/scripts/kappa", line 45, in create
    context.create()
  File "/usr/local/lib/python2.7/dist-packages/kappa-0.3.1-py2.7.egg/kappa/context.py", line 129, in create
    self.role.create()
  File "/usr/local/lib/python2.7/dist-packages/kappa-0.3.1-py2.7.egg/kappa/role.py", line 91, in create
    AssumeRolePolicyDocument=AssumeRolePolicyDocument)
  File "/usr/local/lib/python2.7/dist-packages/botocore-1.1.7-py2.7.egg/botocore/client.py", line 269, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore-1.1.7-py2.7.egg/botocore/client.py", line 310, in _make_api_call
    api_params, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore-1.1.7-py2.7.egg/botocore/client.py", line 351, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore-1.1.7-py2.7.egg/botocore/validate.py", line 273, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter RoleName, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>
make: *** [create] Error 1
```

Also I checked the aws resources, everything is created properly buckets, etc, besides the lambda functions. Then I tried to create lamdas directly with kappa, same error as I had in previous post.
I'm new to lamdas, but I succesfully created, ran and tested kappa's kinesis example, so, my kappa installation seems ok.
Really appreciate your work, I'm almost there, feels like I'm missing something very simple...

**Comment by ryansb** [comment]
Aha! I think I see what is happening. Right [here](https://github.com/ryansb/hugo-lambda/blob/master/Makefile#L27) I use the "shell" builtin to GNU make to get the name of the execution role. It _should_ be outputting the name, something like `"HugoSiteStack-ExecRole-1ICTLZUOLW7HU"` (the name on my deployment).

To remedy this, first run this command:

```
aws cloudformation describe-stack-resources --stack-name HugoSiteStack --logical-resource-id ExecRole --query 'StackResources[0].PhysicalResourceId'
```

Then paste that value into `generate/config.yml` on line 7 as the `name` value. 

Once you've done that, you can manually create the function by doing:

```
kappa config.yml create && kappa config.yml add_event_sources
```

That should get you up and running, then any future updates to the function you can just do "make update". So I can fix this for everyone, can you tell me what shell you are using and what version of make? Also what operating system?

**Comment by vitr** [comment]
alright, this actually helps, got the lamda today! 
I'm using **Ubuntu Trusty** on vagrant's vm
`Linux vagrant-ubuntu-trusty-64 3.13.0-55-generic #92-Ubuntu SMP Sun Jun 14 18:32:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`
shell - **bash**
and the GNU make

```
root@vagrant-ubuntu-trusty-64:/vagrant/hugo-lambda/generate# make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-pc-linux-gnu
```

**Comment by ryansb** [comment]
Great, I'll open a new issue for the makefile incompatibility. Thanks for being patient!

**Comment by mjsweet** [comment]
Hey thanks guys! Will have another go this week :+1:
